apiVersion: v1
kind: ConfigMap
metadata:
  name: identity
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds.Microservices.Identity;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true;Encrypt=False"
  Messaging__Provider: "RabbitMQ"
  Messaging__RabbitMQ__HostName: "rabbitmq"
