services:
  db:
    image: 'mcr.microsoft.com/mssql/server:2025-latest'
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'sqladmin123!@#'
      MSSQL_PID: Developer
      ACCEPT_EULA: 'Y'
      MSSQL_AGENT_ENABLED: 'true'
networks:
  default:
    name: phongnguyend
    external: true
