scrape_configs:
  - job_name: otel-collector
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'otel-collector:8889'
      - targets:
          - 'otel-collector:8888'
  - job_name: webapi
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'host.docker.internal:9002'
